// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptConnection(arg1) {
  return window['go']['main']['App']['AcceptConnection'](arg1);
}

export function CancelTransfers(arg1) {
  return window['go']['main']['App']['CancelTransfers'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function DownloadFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFolder'](arg1, arg2, arg3);
}

export function GetDeviceName() {
  return window['go']['main']['App']['GetDeviceName']();
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetHostName() {
  return window['go']['main']['App']['GetHostName']();
}

export function GetLocalIPs() {
  return window['go']['main']['App']['GetLocalIPs']();
}

export function GetRemoteFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRemoteFiles'](arg1, arg2, arg3);
}

export function GetSessionToken(arg1) {
  return window['go']['main']['App']['GetSessionToken'](arg1);
}

export function GetSharedDir() {
  return window['go']['main']['App']['GetSharedDir']();
}

export function IdentifyDevice(arg1) {
  return window['go']['main']['App']['IdentifyDevice'](arg1);
}

export function MakeDirectory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MakeDirectory'](arg1, arg2, arg3, arg4);
}

export function PushFolderToAndroid(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PushFolderToAndroid'](arg1, arg2, arg3, arg4);
}

export function PushToAndroid(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PushToAndroid'](arg1, arg2, arg3, arg4);
}

export function RejectConnection(arg1) {
  return window['go']['main']['App']['RejectConnection'](arg1);
}

export function RequestConnection(arg1, arg2) {
  return window['go']['main']['App']['RequestConnection'](arg1, arg2);
}

export function SaveDeviceName(arg1) {
  return window['go']['main']['App']['SaveDeviceName'](arg1);
}

export function SaveSharedDir(arg1) {
  return window['go']['main']['App']['SaveSharedDir'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function ShareClipboardText(arg1, arg2) {
  return window['go']['main']['App']['ShareClipboardText'](arg1, arg2);
}
