// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptConnection(arg1:string):Promise<void>;

export function CancelTransfers(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DownloadFolder(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetDeviceName():Promise<string>;

export function GetHomeDir():Promise<string>;

export function GetHostName():Promise<string>;

export function GetLocalIPs():Promise<Array<string>>;

export function GetRemoteFiles(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function GetSessionToken(arg1:string):Promise<string>;

export function GetSharedDir():Promise<string>;

export function IdentifyDevice(arg1:string):Promise<any>;

export function MakeDirectory(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function PushFolderToAndroid(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function PushToAndroid(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function RejectConnection(arg1:string):Promise<void>;

export function RequestConnection(arg1:string,arg2:string):Promise<string>;

export function SaveDeviceName(arg1:string):Promise<void>;

export function SaveSharedDir(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function ShareClipboardText(arg1:string,arg2:string):Promise<void>;
