// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function DownloadFolder(arg1, arg2) {
  return window['go']['main']['App']['DownloadFolder'](arg1, arg2);
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetRemoteFiles(arg1, arg2) {
  return window['go']['main']['App']['GetRemoteFiles'](arg1, arg2);
}

export function IdentifyDevice(arg1) {
  return window['go']['main']['App']['IdentifyDevice'](arg1);
}

export function PushFolderToAndroid(arg1, arg2, arg3) {
  return window['go']['main']['App']['PushFolderToAndroid'](arg1, arg2, arg3);
}

export function PushToAndroid(arg1, arg2, arg3) {
  return window['go']['main']['App']['PushToAndroid'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}
