// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadFile(arg1:string,arg2:string):Promise<string>;

export function DownloadFolder(arg1:string,arg2:string):Promise<string>;

export function GetLocalIP():Promise<string>;

export function GetRemoteFiles(arg1:string,arg2:string):Promise<Record<string, any>>;

export function IdentifyDevice(arg1:string):Promise<main.DeviceIdentity>;

export function PushFolderToAndroid(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PushToAndroid(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFiles():Promise<Array<string>>;
